language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
install:
  - "pip install ."
  - "pip install ujson warcio"
  - "pip install rapidjson || true"
  - "pip install pyspark || true"
addons:
  apt:
    packages:
      - oracle-java8-installer
# command to run tests
script: python -m unittest discover -v
sudo: false
