language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
dist: xenial
before_install:
  - sudo apt-get autoremove openjdk-11-jdk
  - sudo apt-get install openjdk-8-jdk
install:
  - "pip install ."
  - "pip install ujson warcio"
  - "pip install rapidjson || true"
  - "pip install pyspark || true"
  - "echo $JAVA_HOME"
  - "java -version"
  - "update-java-alternatives --list || true"
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#script: python -m unittest discover -v
script: "false"  # fail fast
sudo: false
