language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.8-dev"
  - "nightly"
matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"
  include:
    - python: '3.7'
      dist: xenial
    - python: '3.8-dev'
      dist: xenial
  fast_finish: true
install:
  - "pip install ."
  - "pip install ujson warcio"
  - "pip install rapidjson || true"
# command to run tests
script: python -m unittest discover -v
sudo: false
